### PR TITLE
add activitysim as local directory

### PR DESCRIPTION
**Pull request by toliwaga**
It isn't really clear yet whether out dependency should be on activitysim or just orca. Maybe we want the skim handling capabilities? Or maybe even the bca calculations should eventually be incorporated into activitysim itself. Given the somewhat rudimentary implementation of skim support in activitysim, we will need to extend them. For now, for simplicity, I am just bundling the source until the mist clears.

### CODE REVIEW

**Comment by bstabler** [comment]
I think we want activitysim as well since it has the expressions, model spec, and skim handling.  Although, these appear pretty basic at this point, so maybe we'll end up revising them so much that we'll just create new ones.  Bundling for now makes sense to me.

**Comment by toliwaga** [comment]
Oh right. eval_variables is in activitysim. I haven't really fully internalized the architecture yet.

**Comment by toliwaga** [comment]
The problem with bundling is that travis wants to run the tests in activity, which reference settings files in example dir:

E       IOError: [Errno 2] No such file or directory: '/home/travis/build/RSGInc/bca4abm/activitysim/defaults/test/../../../example/configs/settings.yaml'

Not the tidiest test config in the world, but I am loath to start tweaking activitysim dir byt tossing the test dirs. Maybe I can get py.test to ignore tests in the activitysim subtree with some directive or config spec. But not at 11:00 on Friday night...

**Comment by toliwaga** [comment]
It works to just add the following to setup.cfg in rootdir

[pytest]
norecursedirs= activitysim

**Pull request merged**
